### HTML Form Data

POST http://localhost:8080/request-param
Content-Type: application/x-www-form-urlencoded

username=http-form-gitchan&age=23

### Body String Data

POST http://localhost:8080/request-body-string
Content-Type: text/plain

{
    "body string gitchan!"
}

### Body Json Data

POST http://localhost:8080/request-body-json
Content-Type: application/json

{
  "username": "body json gitchan",
  "age": 23
}
